{{- $cfg := .Values.cnpg -}}
{{- if and $cfg.secrets.app.create ($cfg.secrets.app.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cfg.secrets.app.name }}
  namespace: {{ $cfg.namespace.name }}
  labels:
{{- include "interweb.labels" (dict "root" . "name" $cfg.secrets.app.name "component" "database-credentials") | nindent 4 }}
type: Opaque
data:
  username: {{ $cfg.secrets.app.username | b64enc | quote }}
  password: {{ $cfg.secrets.app.password | b64enc | quote }}
{{- end }}
