{{- $cfg := .Values.minio -}}
{{- if and $cfg.credsSecret.create $cfg.credsSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cfg.credsSecret.name }}
  namespace: {{ $cfg.namespace.name }}
  labels:
{{- include "interweb.labels" (dict "root" . "name" $cfg.credsSecret.name "component" "object-storage-credentials") | nindent 4 }}
type: Opaque
stringData:
  accesskey: {{ $cfg.credsSecret.accessKey | quote }}
  secretkey: {{ $cfg.credsSecret.secretKey | quote }}
{{- end }}
